GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzU2OTMzMjA0LCJleHAiOjE3NTY5MzMyMzR9.BfsqsMboDlDFOPJAzQcjQNxZ1_G2rgTLO20kSBSWMUk


###

GET http://localhost:3000/plants
Content-Type: application/json


###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzU2OTMzMTg0fQ.PpLF-9R8Gpuqo8BQUY0yE_Gl88JLIu6aJ36dTlVm1TQ"
}

###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzU2OTMzMTg0fQ.PpLF-9R8Gpuqo8BQUY0yE_Gl88JLIu6aJ36dTlVm1TQ"
}


###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim",
  "password": "example_password"
}
